require('impatient')

require('pisetski.plugins')
require('pisetski.mappings')
require('pisetski.general')
require('pisetski.nvim-tree')
require('pisetski.lualine')
require('pisetski.cmp')
require('pisetski.lsp')
require('pisetski.null-ls')
require('pisetski.comments')
require('pisetski.treesitter')
require('pisetski.whichkey')
require('pisetski.neogit')
require('pisetski.gitsigns')
require('pisetski.gitlinker')
require('pisetski.autopairs')
require('pisetski.trouble')
