require('pisetski.plugins')
require('pisetski.mappings')
require('pisetski.general')
require('pisetski.plugin-nvim-tree')
require('pisetski.plugin-lualine')
require('pisetski.plugin-telescope')
require('pisetski.plugin-completion')
require('pisetski.lsp')
